### PR TITLE
Feature/tut man detailed view page

### PR DESCRIPTION
**Pull request by HilariousDarious**
- **Added** Detailed View Webpage for Tutoriums --> Shows all Students of a Tutorium **AND** the Tutor **AND** the Tutorium Name
- **Added** Delete Student from Tutorium Button
- **Added** Add Student to Tutorium Button

### CODE REVIEW

**Review by jonaslanglotz — CHANGES_REQUESTED** [review]
Thank you for the effort. I have two things that I would ideally want changed. It would be great if you could implement both, but atleast the first should be possible. 

- [x] Could you remove the border around the student table and move the headings up. Ideally the page would look similar to what @ItsMihail did in #83, I will attach some screenshots. He uses card for the table, but you can leave it like you have.
- [ ] Second, could you maybe implement it so the modal for adding students uses a select-multiple so that we can add multiple students in one go. You could iterate over the list on submit, and send one request for each student. I think this would improve our UX.


Screenshots: 
grafik

**Comment by speedNoah** [comment]
> Thank you for the effort. I have two things that I would ideally want changed. It would be great if you could implement both, but atleast the first should be possible.
> 
>     * [ ]  Could you remove the border around the student table and move the headings up. Ideally the page would look similar to what @ItsMihail did in #83, I will attach some screenshots. He uses card for the table, but you can leave it like you have.
> 
>     * [ ]  Second, could you maybe implement it so the modal for adding students uses a select-multiple so that we can add multiple students in one go. You could iterate over the list on submit, and send one request for each student. I think this would improve our UX.
> 
> 
> Screenshots: grafik

That comment isn´t topic of this merge - please consult Eric, because it`s his topic ^^

**Comment by speedNoah** [comment]
> Thank you for the effort. I have two things that I would ideally want changed. It would be great if you could implement both, but atleast the first should be possible.
> 
>     * [ ]  Could you remove the border around the student table and move the headings up. Ideally the page would look similar to what @ItsMihail did in #83, I will attach some screenshots. He uses card for the table, but you can leave it like you have.
> 
>     * [ ]  Second, could you maybe implement it so the modal for adding students uses a select-multiple so that we can add multiple students in one go. You could iterate over the list on submit, and send one request for each student. I think this would improve our UX.
> 
> 
> Screenshots: grafik

(sorry for the earlier comment - it´s too l8...)
- Considering the first: it is planned, that a absend-view-of-tutorium is displayed on the right-hand side of the detailed-view-box. That`s why the border has been created, to keep both views separated in the end. The Heading is going to be moved above the box - we can agree with that request.
- Considering the second: we are looking forward to add this functionality - please give us some time to figure it out ^^

Best Regards, 
Noah

**Comment by jonaslanglotz** [comment]
Okay, got it. Do you want to make these changes in this PR, or do you want to merge for now?

**Comment by HilariousDarious** [comment]
I changed the page to a similar look to what @ItsMihail did. For the multiple student selection: I think it's better to do another PR.

**Comment by HilariousDarious** [comment]
So it can be merged now ;)

**Review by EricZimmer1 — COMMENTED** [review]
Looks good to me @jonaslanglotz what do you think?

**Review by jonaslanglotz — APPROVED** [review]

**Pull request merged**
